# Generated by Django 4.1.3 on 2022-12-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='allert',
            new_name='important',
        ),
        migrations.RemoveField(
            model_name='todos',
            name='date_todo',
        ),
        migrations.RemoveField(
            model_name='todos',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='todos',
            name='pub_time',
        ),
        migrations.RemoveField(
            model_name='todos',
            name='time_todo',
        ),
        migrations.AddField(
            model_name='todos',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='todos',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='todos',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
