# Generated by Django 4.1.3 on 2022-12-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_allert_todos_important_remove_todos_date_todo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time todo this'),
        ),
    ]
